version: '3.2'

services:

  postgresql_test:
    build: docker/postgres/.
    env_file:
      - env/test.pg.env
    ports:
      - '5455:5432'
    networks:
      - iposter_network_test
    volumes:
      - pg_data_test:/var/lib/postgresql/data

  # minio_test:
  #   image: minio/minio
  #   entrypoint: sh
  #   command: -c 'mkdir -p /export/images && /usr/bin/minio server /export'
  #   env_file:
  #     - env/test.minio.env
  #   ports:
  #     - '9001:9000'
  #   networks:
  #     - iposter_network_test
  #   volumes:
  #     - minio_data_test:/var/lib/minio/data

  minio_test:
    image: "minio/minio"
    restart: always
    networks:
      - iposter_network_test
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data_test:/data
    command: "server --console-address :9001 /data"
    env_file:
      - env/local.minio.env

volumes:
  pg_data_test:
  minio_data_test:

networks:
  iposter_network_test:
    driver: bridge
